[package]
name = "elm-init"
version = "0.1.0"
authors = ["abab <ababup1192@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sailfish = "0.3.3"
clap = "2.33.3"